variables:
  RESOURCE_GROUP:
    description: "the resource group name"
    value: "IeCAG-INFCA"
  DEPLOY:
    description: "Deploying the infrastructure"
    value: "false"
  NUKE:
    description: "Nuke the resource group"
    value: "false"
  STORAGE_ACCOUNT:
    description: "the storage account name"
    value: "iecagstorage"
  TABLE_CURRENT_PRICE:
    description: "current price table name"
    value: "currentprices"
  TABLE_PRICE_HISTORY_7DAYS:
    description: "price history table last 7 Days"
    value: "pricehistory7days"
  TABLE_PRICE_HISTORY_30DAYS:
    description: "price history table last 30 Days"
    value: "pricehistory30days"
  TABLE_PRICE_HISTORY_180DAYS:
    description: "price history table last 180 Days"
    value: "pricehistory180days"
  TABLE_LOGS:
    description: "logs table"
    value: "logs"
  TABLE_USERS:
    description: "users table"
    value: "users"
  TABLE_TRANSACTIONS:
    description: "transactions table"
    value: "transactions"
  TABLE_NOTIFICATIONS:
    description: "notifications table"
    value: "notifications"
  APPSERVICE_PLAN_NAME:
    description: "app service plan name"
    value: "iecagAppServicePlan"
  APPSERVICE_WRAPPER_PLAN_NAME:
    description: "app service plan name"
    value: "iecagwrapperAppServicePlan"
  WEBAPP_NAME:
    description: "web app name"
    value: "iecag"
  WEBAPP_PATH:
    description: "web app path"
    value: "/app.zip"
  CONTAINER_ENV:
    description: "container environment"
    value: "iecagenv"
  AZURE_LOCATION:
    description: "azure region to deploy to"
    value: "eastus"
  WRAPPER_CONTAINER_NAME:
    description: "container name of api_wrapper"
    value: "iecagapiwrapper"
  WRAPPER_DIR:
    description: "path to api_wrapper"
    value: "./code/api_wrapper"
  CONTAINER_REGISTRY_NAME:
    description: "container registry"
    value: "iecagconreg"
  APPLICATION_INSIGHTS_NAME:
    description: "application insights name"
    value: "iecagAppServiceApplicationInsights"
  SENDGRID_API_KEY:
    description: "sendgrid api key"
    value: ""


stages:
  - azure_setup
  - build
  - deploy

default:
  image: inf-docker.fh-rosenheim.de/inf-ca/sose2024/iecag/azure-cli
  before_script:
    - az login --service-principal --username $SP_ID --password $SP_SECRET --tenant $SP_TENANT_ID
    - az account set --subscription $SUBSCRIPTION_ID
    - set -euo pipefail

tilly_nuke:
  stage: azure_setup
  image: inf-docker.fh-rosenheim.de/inf-ca/sose2024/iecag/azure-cli
  allow_failure: true
  script:
    - if [ $NUKE == "true" ]; then az group delete --yes --name $RESOURCE_GROUP; fi || exit 0
  rules:
    - if: '$DEPLOY == "true"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

terraform:
  stage: deploy
  image: 
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script: 
    - apk update && apk add ca-certificates
    - mkdir -p /etc/ssl/certs
    - cp $CI_PROJECT_DIR/terraform/.thro.crt /etc/ssl/certs/custom-ca-bundle.crt
    - update-ca-certificates
  script:
    - cd terraform 
    - terraform init
    - terraform plan -var="client_id=$SP_ID" -var="client_secret=$SP_SECRET" -var="tenant_id=$SP_TENANT_ID" -var="subscription_id=$SUBSCRIPTION_ID" -var="ci_registry=$CI_REGISTRY" -var="ci_registry_user=$CI_REGISTRY_USER" -var="ci_registry_pw=$CI_REGISTRY_PASSWORD" -out=tfplan
    - terraform apply -auto-approve
  artifacts:
    paths:
      - terraform/tfplan
  needs:
    - tilly_nuke
  rules:
    - if: '$DEPLOY == "true"'
  when: manual

# azure_setup job could "fail" due to resources already existing.
# This could be checked for, but currently I am just happy to have fixed the azure-cli certificate problem.
# The allow_failure documents some allowed exit codes.
# And yes, the `|| exit 0` is terrible, but it makes the pipeline a pretty green.

# Not pretty, but practical: the docker executor takes too long to run the setup in separate steps
azure_create_resource_group_datatable_appserviceplan_webapp:
  stage: azure_setup
  allow_failure:
    exit_codes:
      - 0
      - 1
  needs:
    - tilly_nuke
  script:
    - az group create -n $RESOURCE_GROUP -l westeurope || exit 0
    - echo "Creating datatable"
    - az storage account create -n $STORAGE_ACCOUNT -g $RESOURCE_GROUP -l westus --subscription $SUBSCRIPTION_ID || exit 0
    - AZURE_STORAGE_ACCOUNT_KEY=$(az storage account keys list --account-name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP | jq -r .[0].value) || exit 0
    - echo ${#AZURE_STORAGE_ACCOUNT_KEY}
    - az storage table create --name $TABLE_CURRENT_PRICE --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_PRICE_HISTORY_7DAYS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_PRICE_HISTORY_30DAYS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_PRICE_HISTORY_180DAYS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_LOGS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_USERS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_TRANSACTIONS --account-name $STORAGE_ACCOUNT || exit 0
    - az storage table create --name $TABLE_NOTIFICATIONS --account-name $STORAGE_ACCOUNT || exit 0
    - echo "Creating Application Insight for webapp"
    - az monitor app-insights component create --app $APPLICATION_INSIGHTS_NAME --resource-group $RESOURCE_GROUP --location $AZURE_LOCATION
    - APP_INSIGHTS_CONNECTION_STRING=$(az monitor app-insights component show --app $APPLICATION_INSIGHTS_NAME --resource-group $RESOURCE_GROUP --query connectionString -o tsv)
    - echo "Creating appserviceplan"
    - az appservice plan create --name $APPSERVICE_PLAN_NAME --resource-group $RESOURCE_GROUP --sku F1 || exit 0
    - az appservice plan create --name $APPSERVICE_WRAPPER_PLAN_NAME --is-linux --resource-group $RESOURCE_GROUP --sku F1 || exit 0
    - echo "Creating webapp"
    - STORAGE_CONNECTION_STRING=$(az storage account show-connection-string --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP --query connectionString -o tsv)
    - az webapp create --resource-group $RESOURCE_GROUP --plan $APPSERVICE_PLAN_NAME --name $WEBAPP_NAME --runtime "dotnet:8" || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --settings ConnectionStrings__AzureStorage=$STORAGE_CONNECTION_STRING || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --settings ConnectionStrings__ApplicationInsights=$APP_INSIGHTS_CONNECTION_STRING || exit 0
    - az webapp config set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --web-sockets-enabled true || exit 0
    - echo "Creating wrapper"
    - AZURE_ACCESS_KEY=$(az storage account show-connection-string --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP --query connectionString --output tsv)
    - az webapp create --resource-group $RESOURCE_GROUP --plan $APPSERVICE_WRAPPER_PLAN_NAME --name $WRAPPER_CONTAINER_NAME --runtime "PYTHON:3.10" || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings AZURE_ACCESS_KEY=$AZURE_ACCESS_KEY || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings COINGECKO_TOKEN=$COINGECKO_TOKEN || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings AZURE_ACCOUNT_NAME=$STORAGE_ACCOUNT || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings AZURE_CONNECTION_STRING=$STORAGE_CONNECTION_STRING || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true || exit 0
    - az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --settings WEBSITES_PORT=8080 || exit 0
  rules:
    - if: '$DEPLOY == "true"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

azure_build_webapp:
  stage: azure_setup
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - echo "Building webapp"
  script:
    - apt update && apt install -y zip
    - cd code/WebApp/
    - dotnet publish -c Release -o out
    - cd out
    - zip -r app.zip .
  artifacts:
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - code/WebApp/out/app.zip

azure_build_wrapper:
  stage: azure_setup
  image: python:3.10
  before_script:
    - echo "Building wrapper"
  script:
    - apt update && apt install -y zip
    - cd $WRAPPER_DIR
    - python -m venv venv
    - . venv/bin/activate && pip install -r requirements.txt
    - zip -r app.zip .
  artifacts:
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - code/api_wrapper/app.zip

azure_deploy_webapp:
  stage: azure_setup
  allow_failure: true
  needs:
    - azure_create_resource_group_datatable_appserviceplan_webapp
    - azure_build_webapp
    - azure_build_wrapper
  script:
    - az webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --src code/WebApp/out/app.zip || exit 0
    - az webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --src code/api_wrapper/app.zip || exit 0

azure_notifications:
  stage: azure_setup
  allow_failure: true
  needs:
    - azure_deploy_webapp
  script:
    - echo "Setup notifications"
    - az functionapp create --resource-group $RESOURCE_GROUP --consumption-plan-location westus --os-type linux --runtime python --runtime-version 3.10 --functions-version 4 --name HealthAndPrice --storage-account $STORAGE_ACCOUNT || exit 0
    

#build_api_wrapper:
#  stage: azure_setup
#  image: docker:latest
#  services:
#    - docker:dind
#  before_script:
#    - echo $CI_JOB_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#  script:
#    - cd $WRAPPER_DIR
#    - docker build -t "$CI_REGISTRY_IMAGE/api_wrapper" .
#    - docker push "$CI_REGISTRY_IMAGE/api_wrapper"

# azure_deploy_wrapper:
#   stage: azure_setup
#   allow_failure: true
#   needs:
#     - azure_create_datatable
#     #- build_api_wrapper
#   script:
#     - az acr create --resource-group $RESOURCE_GROUP --name $CONTAINER_REGISTRY_NAME --sku Basic --admin-enabled true || exit 0
#     - ACR_LOGIN_SERVER=$(az acr show --name $CONTAINER_REGISTRY_NAME --resource-group $RESOURCE_GROUP --query loginServer --output tsv)
#     - ACR_USERNAME=$(az acr credential show --name $CONTAINER_REGISTRY_NAME --query "username" --output tsv)
#     - ACR_PASSWORD=$(az acr credential show --name $CONTAINER_REGISTRY_NAME --query "passwords[0].value" --output tsv)
#     - cd $WRAPPER_DIR
#     - az acr build --image api_wrapper:latest --registry $ACR_LOGIN_SERVER --file Dockerfile .

#     #- az containerapp env create --name $CONTAINER_ENV --resource-group $RESOURCE_GROUP --location $AZURE_LOCATION || exit 0
#     - AZURE_ACCESS_KEY="$(az storage account keys list --account-name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP | jq -r .[0].value)"
#     #- AZURE_ACCESS_KEY=$(az storage account show-connection-string --name $STORAGE_ACCOUNT_NAME --resource-group $RESOURCE_GROUP --query connectionString --output tsv)
#     - echo ${#AZURE_ACCESS_KEY}
#     #- az containerapp up -n $WRAPPER_CONTAINER_NAME --image $CI_REGISTRY_IMAGE/api_wrapper:latest --ingress external --target-port 8080 --environment $CONTAINER_ENV --registry-server "$CI_REGISTRY" --registry-password "$CI_REGISTRY_PASSWORD" --registry-username "$CI_REGISTRY_USER" --env-vars COINGECKO_TOKEN=$COINGECKO_TOKEN AZURE_ACCOUNT_NAME=$STORAGE_ACCOUNT AZURE_ACCESS_KEY=$AZURE_ACCESS_KEY || exit 0
#     - az container create --resource-group $RESOURCE_GROUP --name $WRAPPER_CONTAINER_NAME --image $CONTAINER_REGISTRY_NAME.azurecr.io/api_wrapper:latest --cpu 1 --memory 1 --registry-login-server $CONTAINER_REGISTRY_NAME.azurecr.io --registry-username $ACR_USERNAME --registry-password$ACR_PASSWORD --dns-name-label $WRAPPER_CONTAINER_NAMEdns --ingress external --target-port 8080

